export const CALL_API_PENDING = "CALL_API_PENDING";

export const GET_LIST_MATCHS_FULFILLED = "GET_LIST_MATCHS_FULFILLED";
export const GET_LIST_MATCHS_REJECTED = "GET_LIST_MATCHS_REJECTED";
export const SET_TEAM_WIN_FULFILLED = "SET_TEAM_WIN_FULFILLED";
export const SET_TEAM_WIN_REJECTED = "SET_TEAM_WIN_REJECTED";
export const CHANGE_TEXT_SEARCH_MATCH = "CHANGE_TEXT_SEARCH_MATCH";

export const GET_MATCH_DETAIL_FULFILLED = "GET_MATCH_DETAIL_FULFILLED";
export const GET_MATCH_DETAIL_REJECTED = "GET_MATCH_DETAIL_REJECTED";

export const NEXT_STEP_FORM = "NEXT_STEP_FORM";
export const BACK_STEP_FORM = "BACK_STEP_FORM";
export const CHANGE_VALUE_FORM = "CHANGE_VALUE_FORM";
export const CHANGE_ERROR_CREATE_MATCH = "CHANGE_ERROR_CREATE_MATCH";
export const SET_FORM_MATCH_EDIT = "SET_FORM_MATCH_EDIT";
export const CHANGE_ERROR_EDIT_MATCH = "CHANGE_ERROR_EDIT_MATCH";

export const CHANGE_ERROR_ACTION_USER = "CHANGE_ERROR_ACTION_USER";
export const OPEN_FORM_CREATE_USER = "OPEN_FORM_CREATE_USER";
export const CHANGE_VALUE_FORM_USER_ACTION = "CHANGE_VALUE_FORM_USER_ACTION";
export const CLEAR_ALL_FORM_USER_ACTION = "CLEAR_ALL_FORM_USER_ACTION";
export const GET_LIST_USERS_FULFILLED = "GET_LIST_USERS_FULFILLED";
export const GET_LIST_USERS_REJECTED = "GET_LIST_USERS_REJECTED";
export const GET_USER_DETAIL_FULFILLED = "GET_USER_DETAIL_FULFILLED";
export const GET_USER_DETAIL_REJECTED = "GET_USER_DETAIL_REJECTED";
export const CREATE_USER_FULFILLED = "CREATE_USER_FULFILLED";
export const CREATE_USER_REJECTED = "CREATE_USER_REJECTED";
export const EDIT_USER_FULFILLED = "EDIT_USER_FULFILLED";
export const EDIT_USER_REJECTED = "EDIT_USER_REJECTED";
export const DELETE_USER_FULFILLED = "DELETE_USER_FULFILLED";
export const DELETE_USER_REJECTED = "DELETE_USER_REJECTED";
export const CHANGE_TEXT_SEARCH_USER = "CHANGE_TEXT_SEARCH_USER";
export const SET_USER_SELECTED = "SET_USER_SELECTED";
export const GENERATE_TEAM_TO_MATCH_FULFILLED = "GENERATE_TEAM_TO_MATCH_FULFILLED";
export const GENERATE_TEAM_TO_MATCH_REJECTED = "GENERATE_TEAM_TO_MATCH_REJECTED";
export const CANCEL_CREATE_MATCH = "CANCEL_CREATE_MATCH";
export const CREATE_MATCH_FULFILLED = "CREATE_MATCH_FULFILLED";
export const CREATE_MATCH_REJECTED = "CREATE_MATCH_REJECTED";
export const DELETE_MATCH_FULFILLED = "DELETE_MATCH_FULFILLED";
export const DELETE_MATCH_REJECTED = "DELETE_MATCH_REJECTED";
export const EDIT_MATCH_FULFILLED = "EDIT_MATCH_FULFILLED";
export const EDIT_MATCH_REJECTED = "EDIT_MATCH_REJECTED";
export const CLEAR_FORM_EDIT_MATCH = "CLEAR_FORM_EDIT_MATCH";
